<?php

namespace Tests\Unit;

use App\Services\OpenAiService;
use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class OpenAiServiceTest extends TestCase
{
    /**
     * Test service generates contract description from OpenAI API.
     */
    public function test_generates_contract_description(): void
    {
        Http::fake([
            'api.openai.com/v1/chat/completions' => Http::response([
                'choices' => [
                    [
                        'message' => [
                            'content' => 'Test description generated by OpenAI.',
                        ],
                    ],
                ],
            ], 200),
        ]);

        $service = new OpenAiService();
        $description = $service->generateDescription('Test prompt');

        $this->assertEquals('Test description generated by OpenAI.', $description);
    }

    /**
     * Test service uses correct API endpoint and model.
     */
    public function test_uses_correct_api_endpoint_and_model(): void
    {
        Http::fake([
            'api.openai.com/v1/chat/completions' => Http::response([
                'choices' => [
                    [
                        'message' => [
                            'content' => 'Test description.',
                        ],
                    ],
                ],
            ], 200),
        ]);

        $service = new OpenAiService();
        $service->generateDescription('Test prompt');

        Http::assertSent(function (Request $request) {
            $body = json_decode($request->body(), true);
            return $request->url() === 'https://api.openai.com/v1/chat/completions'
                && $body['model'] === 'gpt-4'
                && $body['messages'][0]['role'] === 'user'
                && $body['messages'][0]['content'] === 'Test prompt';
        });
    }

    /**
     * Test service sends correct authorization header.
     */
    public function test_sends_authorization_header(): void
    {
        config(['services.openai.api_key' => 'test-api-key']);

        Http::fake([
            'api.openai.com/v1/chat/completions' => Http::response([
                'choices' => [
                    [
                        'message' => [
                            'content' => 'Test description.',
                        ],
                    ],
                ],
            ], 200),
        ]);

        $service = new OpenAiService();
        $service->generateDescription('Test prompt');

        Http::assertSent(function (Request $request) {
            return $request->hasHeader('Authorization', 'Bearer test-api-key');
        });
    }

    /**
     * Test service throws exception on API error.
     */
    public function test_throws_exception_on_api_error(): void
    {
        Http::fake([
            'api.openai.com/v1/chat/completions' => Http::response([
                'error' => [
                    'message' => 'API Error',
                ],
            ], 500),
        ]);

        $this->expectException(\Illuminate\Http\Client\RequestException::class);

        $service = new OpenAiService();
        $service->generateDescription('Test prompt');
    }

    /**
     * Test service retries on temporary failures.
     */
    public function test_retries_on_temporary_failures(): void
    {
        $attempts = 0;
        Http::fake(function ($request) use (&$attempts) {
            $attempts++;
            if ($attempts < 3) {
                return Http::response(['error' => 'Temporary Error'], 503);
            }
            return Http::response([
                'choices' => [
                    [
                        'message' => [
                            'content' => 'Success after retry.',
                        ],
                    ],
                ],
            ], 200);
        });

        $service = new OpenAiService();
        $description = $service->generateDescription('Test prompt');

        $this->assertEquals('Success after retry.', $description);
        $this->assertEquals(3, $attempts);
    }

    /**
     * Test contract prompt builder creates correct prompt.
     */
    public function test_builds_contract_prompt_with_all_fields(): void
    {
        $contractData = [
            'company_name' => 'Test Company Oy',
            'contract_name' => 'Test Contract 12kk',
            'contract_type' => 'Fixed',
            'metering' => 'General',
            'price_components' => [
                ['type' => 'General', 'price' => 10.5, 'unit' => 'snt/kWh'],
                ['type' => 'Monthly', 'price' => 4.99, 'unit' => 'EUR/kk'],
            ],
            'electricity_source' => [
                'renewable_wind' => 50.0,
                'nuclear_general' => 30.0,
            ],
            'consumption_limit' => null,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('Test Company Oy', $prompt);
        $this->assertStringContainsString('Test Contract 12kk', $prompt);
        $this->assertStringContainsString('Fixed', $prompt);
        $this->assertStringContainsString('General', $prompt);
        $this->assertStringContainsString('10.5', $prompt);
        $this->assertStringContainsString('4.99', $prompt);
        $this->assertStringContainsString('renewable_wind', $prompt);
        $this->assertStringContainsString('nuclear_general', $prompt);
    }

    /**
     * Test prompt builder includes consumption limit when present.
     */
    public function test_builds_prompt_with_consumption_limit(): void
    {
        $contractData = [
            'company_name' => 'Test Company',
            'contract_name' => 'Test Contract',
            'contract_type' => 'Fixed',
            'metering' => 'General',
            'price_components' => [
                ['type' => 'General', 'price' => 10.0, 'unit' => 'snt/kWh'],
            ],
            'electricity_source' => [],
            'consumption_limit' => 5000,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('5000', $prompt);
        $this->assertStringContainsString('kWh', $prompt);
    }

    /**
     * Test prompt builder handles spot contract pricing.
     */
    public function test_builds_prompt_for_spot_contract(): void
    {
        $contractData = [
            'company_name' => 'Test Company',
            'contract_name' => 'Pörssisähkö',
            'contract_type' => 'Spot',
            'metering' => 'General',
            'price_components' => [
                ['type' => 'General', 'price' => 0.49, 'unit' => 'snt/kWh'],
                ['type' => 'Monthly', 'price' => 3.99, 'unit' => 'EUR/kk'],
            ],
            'electricity_source' => [],
            'consumption_limit' => null,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('Spot', $prompt);
        $this->assertStringContainsString('marginaali', $prompt);
    }

    /**
     * Test prompt builder handles time-based metering.
     */
    public function test_builds_prompt_for_time_metering(): void
    {
        $contractData = [
            'company_name' => 'Test Company',
            'contract_name' => 'Aikasähkö',
            'contract_type' => 'OpenEnded',
            'metering' => 'Time',
            'price_components' => [
                ['type' => 'DayTime', 'price' => 12.0, 'unit' => 'snt/kWh'],
                ['type' => 'NightTime', 'price' => 8.0, 'unit' => 'snt/kWh'],
                ['type' => 'Monthly', 'price' => 4.50, 'unit' => 'EUR/kk'],
            ],
            'electricity_source' => [],
            'consumption_limit' => null,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('DayTime', $prompt);
        $this->assertStringContainsString('NightTime', $prompt);
        $this->assertStringContainsString('12', $prompt);
        $this->assertStringContainsString('8', $prompt);
    }

    /**
     * Test prompt builder handles seasonal metering.
     */
    public function test_builds_prompt_for_seasonal_metering(): void
    {
        $contractData = [
            'company_name' => 'Test Company',
            'contract_name' => 'Kausisähkö',
            'contract_type' => 'OpenEnded',
            'metering' => 'Seasonal',
            'price_components' => [
                ['type' => 'SeasonalWinter', 'price' => 15.0, 'unit' => 'snt/kWh'],
                ['type' => 'SeasonalOther', 'price' => 10.0, 'unit' => 'snt/kWh'],
                ['type' => 'Monthly', 'price' => 4.50, 'unit' => 'EUR/kk'],
            ],
            'electricity_source' => [],
            'consumption_limit' => null,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('SeasonalWinter', $prompt);
        $this->assertStringContainsString('SeasonalOther', $prompt);
        $this->assertStringContainsString('15', $prompt);
        $this->assertStringContainsString('10', $prompt);
    }

    /**
     * Test prompt includes Finnish language instruction.
     */
    public function test_prompt_includes_finnish_language_instruction(): void
    {
        $contractData = [
            'company_name' => 'Test Company',
            'contract_name' => 'Test Contract',
            'contract_type' => 'Fixed',
            'metering' => 'General',
            'price_components' => [
                ['type' => 'General', 'price' => 10.0, 'unit' => 'snt/kWh'],
            ],
            'electricity_source' => [],
            'consumption_limit' => null,
        ];

        $service = new OpenAiService();
        $prompt = $service->buildContractPrompt($contractData);

        $this->assertStringContainsString('Finnish', $prompt);
    }
}
